[[plugins]]
repo = 'easymotion/vim-easymotion'
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
[[plugins]]
repo = 'nvim-lua/completion-nvim'
[[plugins]]
repo = 'neovim/nvim-lspconfig'
[[plugins]]
repo = 'github/copilot.vim'
[[plugins]]
repo = 'APZelos/blamer.nvim'
[[plugins]]
repo = 'wakatime/vim-wakatime'
#[[plugins]]
#repo = '4513ECHO/vim-colors-hatsunemiku'
[[plugins]]
repo = 'shaunsingh/moonlight.nvim'
[[plugins]]
repo = 'sainnhe/edge'
[[plugins]]
repo = 'hrsh7th/vim-vsnip'
[[plugins]]
 repo = 'hrsh7th/vim-vsnip-integ'
[[plugins]]
repo = 'ryanoasis/vim-devicons'
[[plugins]]
repo = 'simeji/winresizer'
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
[[plugins]]
repo = 'IMOKURI/line-number-interval.nvim'
